### ISSUE TITLE
Erreur CMake

### ISSUE THREAD

**Issue by kilbith** [Unarelith/OpenMiner#108]
Après un `git clone --recursive` et `cmake -B build . && cmake --build build -j4` :

```
-- UDev not found.
-- UDev: You can specify includes: -DUDEV_PATH_INCLUDES=/opt/udev/include
--       currently found includes: UDEV_INCLUDE_DIR-NOTFOUND
-- UDev: You can specify libs: -DUDEV_PATH_LIB=/opt/udev/lib
--       currently found libs: UDEV_LIBRARIES-NOTFOUND
CMake Error at external/gamekit/external/SFML/cmake/Modules/FindUDev.cmake:49 (MESSAGE):
  Could not find UDev library
Call Stack (most recent call first):
  external/gamekit/external/SFML/cmake/Macros.cmake:364 (find_package)
  external/gamekit/external/SFML/src/SFML/Window/CMakeLists.txt:282 (sfml_find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by Unarelith** [comment]
Please write your issues in english. Especially when it's about a problem other people could have.
And please provide information relative to your OS/type of machine instead of expecting people to just guess what's wrong with your system. 

Have you tried to install `libudev-dev` or similar? Check the dependency list for Debian/Ubuntu [here](https://github.com/Unarelith/OpenMiner/blob/master/.travis.yml#L13-L25)

**Comment by kilbith** [comment]
I was missing a few libs on Ubuntu 20.04 but they weren't mentionned in the doc.

**Comment by Unarelith** [comment]
[Linux compilation doc added](https://github.com/Unarelith/OpenMiner/wiki/Compiling-on-Linux) in answer to this issue.
