### ISSUE TITLE
Items can be duplicated

### ISSUE THREAD

**Issue by Dima8249** [Unarelith/OpenMiner#144]
There is a way to copy things through the workbench.

What I did:
1) Make the desired item in the workbench
2) After I've made it, I take it out of the slot and swap it with some item on the quick panel of blocks (right after crafting, not putting it in any slot, namely swapping it with some item)
3) After a while, I looked again at the same workbench and there was a item of a recently made item (i.e. + item or resources)

I tried to open the workbench immediately after crafting, but it was still empty

**Comment by Unarelith** [comment]
I found another issue so it's not only the workbench.

The exact steps I did:
- Right-click drag a stack of 64 items on the three slots on the right
- Left-click drag the stack on all of the other emply slots (but not in the hotbar)
- Left-click drag the rest on the three slots on the right
- Shift-click all of them and you'll have 77 items instead of 64
